spring:
  application:
    name: limite-service
  data:
    mongodb:
      host: localhost
      port: 27017
  redis:
    host: localhost
    port: 6379
  cloud:
    function:
      definition: limite
    stream:
      bindings:
        limite-in-0:
          group: '${spring.application.name}'
          destination: limite-topic
          content-type: application/json
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
    listener:
      missing-topics-fatal: false
    producer:
      retries: 3
      client-id: ${spring.application.name}
      transaction-id-prefix: ted

server:
  port: 9090