create table IF NOT EXISTS banco(
id bigint not null GENERATED BY DEFAULT AS IDENTITY,
code varchar(10) not null,
descricao varchar(50) not null,
primary key (id),
UNIQUE(code)
);

create table IF NOT EXISTS conta(
id bigint not null GENERATED BY DEFAULT AS IDENTITY,
numero varchar(10) not null,
banco_id bigint not null,
cliente varchar(14),
primary key (id),
foreign key (banco_id) references banco (id)
);

create table IF NOT EXISTS extrato (
id bigint not null GENERATED BY DEFAULT AS IDENTITY,
conta_id bigint not null,
data timestamp,
saldo numeric(15,4),
operacao varchar(50) not null,
valor numeric(15,4),
foreign key (conta_id) references conta(id),
primary key (id)
);